### ISSUE TITLE
Flip PC104 connector pins

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/CubeSat-Radio#27]
Although the library component for the PC104 connector was updated, the change did not propagate to the RF board:
<img width="512" alt="rf board pc104" src="https://user-images.githubusercontent.com/24886818/27748319-de5ce38a-5d83-11e7-89d5-01647c0082c8.png">
Row B should be on the left row B on the right.

**Comment by richarthurs** [comment]
Fixed

**Comment by richarthurs** [comment]
Updated component in library, needs to be changed on RF PCB

**Comment by TobiNakamura** [comment]
PC/104 back plane rotated such that A side is closest to edge
