### ISSUE TITLE
Formalise Antenna Connection

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio#30]
Confirm with Structural regarding placement of SMA connector

**Comment by TobiNakamura** [comment]
Connector should go on the -x side of the board (opposite to PC/104 bus) and 2.5cm off from the center.
This placement will facilitate securing the cable to the board after the end plate has been put onto the cubesat via a small access panel. Tweezers with rubber tips will be required the screw the cable in.

**Comment by Alenux55** [comment]
Please provide a coordinates for the SMA connector with respect to the PC104 connector

**Comment by TobiNakamura** [comment]
SMA has been fixed to the required location on the board.

**Comment by Alenux55** [comment]
@TobiNakamura can we close this issue?
