### ISSUE TITLE
RF Switching

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio#39]
Currently a the architecture is
antenna --- diplexer --- Switch --- PA
                        |                  |
                Upper band     LNA

This introduced ~0.5db of attenuation at the diplexer and a further 0.5db at the switch. If we eliminate the switch and use a SP4T RF switch we can reduce the total loss to 0.5db

http://www.skyworksinc.com/uploads/documents/SKY13388_465LF_201403H.pdf

**Comment by TobiNakamura** [comment]
Even if we dont go with this architecture we still need a 2W rated SPDT switch

**Comment by TobiNakamura** [comment]
@Alenux55 added SKY13345-368LF in conjunction with CD4555B to replace the diplexer.
![image](https://user-images.githubusercontent.com/10017555/37633653-7e3c62e0-2bb0-11e8-8ead-674176fdf113.png)

**Comment by TobiNakamura** [comment]
@Alenux55 What do you think about using Q3 as an error output?

**Comment by Alenux55** [comment]
Like to display it on an LED?

**Comment by Alenux55** [comment]
@TobiNakamura I am going to close this unless we can think of something to use for the extra outputs

**Comment by Alenux55** [comment]
Closing.
