### ISSUE TITLE
Add DC Barrel Jack for Vin

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio#46]
Component: 3pin-DC-power
Footprint: SFUSat:PJ-028-SMT-TR-3pin-DC-jack
Center pin positive: +V on pin 1

**Comment by Alenux55** [comment]
Added.

![barrel jack vin](https://user-images.githubusercontent.com/24886818/39166640-976952be-473f-11e8-8165-e283a3db4134.png)
