### ISSUE TITLE
Remove OP_3v3 jumper

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio#53]
![image](https://user-images.githubusercontent.com/10017555/39146061-83f2db2e-46ea-11e8-8458-fc4058b0ce66.png)
This feature make the power plane more complex. We can remove it and connect VDD to the main 3v3 rail. If the debugger is to provide power you can apply it directly to the 3v3 pin in the PC104 bus.

**Comment by Alenux55** [comment]
Are we able to turn off the debugger's output power? If not, do we anticipate never needing to control the board with the CC debugger and powering it from the PC104 stack?

**Comment by TobiNakamura** [comment]
http://www.ti.com/lit/ug/swru197h/swru197h.pdf
Schematic on appendix A. Pin 9 of the CC-Debugger header is permanently connected to 3v3.
I think the only use case for the CC-debugger is initial bring-up. So probing the CC1101 output.

**Comment by TobiNakamura** [comment]
Pin 9 (OP_3.3) has been disconnected. 3.3v net of CC1101.sch now connected to board wide 3V3 net.
