### ISSUE TITLE
Manual Gain Control

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio#54]
Gain control using the potentiometer should vary the output between 0 and 3.1V.
This can be done linearly using only a potentiometer, however we are only interested in using the circuit with an output above ~2V. A non-linear circuit can be constructed to maximise the resolution around the desired output voltage.
![image](https://user-images.githubusercontent.com/10017555/39284567-c973d8ee-48c8-11e8-808d-a12ee4f6e580.png)
Note R411 and R412 exists to replace the potentiometer in case a fixed value is desired.

![image](https://user-images.githubusercontent.com/10017555/39284675-48d401ea-48c9-11e8-81eb-cb0971b6e2d5.png)
The x-axis is the fraction of wiper position along the length of the rail, y is the output voltage. The non-linearity of the output can be controlled using R_2. I suggest we use R_2 = 100k ohms.

**Comment by TobiNakamura** [comment]
100k 0402 res added

**Comment by Alenux55** [comment]
Done.
