### ISSUE TITLE
Replace LED Current limiting res with array

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio#59]
https://www.digikey.ca/products/en/resistors/resistor-networks-arrays/50?k=&pkeyword=resistor+array&pv1=291&FV=ffe00032&quantity=0&ColumnSort=0&page=1&pageSize=25

**Comment by Alenux55** [comment]
I think it's just as easy to use individual resistors, and more options for alternatives. More interested in consolidating BOM line items than quantity
